config/routes.rb
Rails.application.routes.draw do
 
 get '/blogs/new' => 'blog#new', as: 'new_blog'
 get '/blogs/:id' => 'blog#show', as: 'blog'
 get '/blogs/:id/edit' => 'blog#edit', as: 'edit_blog'
 get '/blogs' => 'blog#index', as: 'blogs'
 patch '/blogs/:id' => 'blog#update'
 post '/blogs' => 'blog#create'
 delete '/blogs/:id' => 'blog#delete', as: 'delete_blog'
 root 'blog#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
    validates :title, :content, presence: true
    validates :title, uniqueness: true
    validates :title, length: { minimum: 4 }
    validates :content, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
        def index
            @blogs = Blog.all
        end

        def show
            @blog = Blog.find(params[:id])
        end

        def new
            @blog = Blog.new
        end

        def create
            @blog = Blog.create(blog_params)
        end

        def delete
            @blog = Blog.find(params[:id])
            if @blog.destroy
                redirect_to blogs_path
            end
        end 

        def edit
            @blog = Blog.find(params[:id])
        end

        def update
            @blog = Blog.find(params[:id])
            if @blog.update(blog_params)
                redirect_to blogs_path(@blog)
            end
        end

private
        def blog_params
            params.require(:blog).permit(:title, :content)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/edit.html.erb
<h1>Edit A Blog</h1>

<%= form_with model: @blog, method: :patch do |form| %>
    <%= form.label :title %>
    <%= form.text_field :title %>
        <br />
    <%= form.label :content %>
    <%= form.text_field :content %>
        <br />
    <%= form.submit 'Edit Blog' %>
<% end %>
        <br />
 <%= link_to 'back to main page', blogs_path %>

 

app/views/blog/index.html.erb
<h1> Here Are Our Blogs </h1>
<ul>
    <% @blogs.each do |blog| %>
    <li> <%= link_to blog.title, blog_path(blog) %> </li>    
    <% end %>
</ul>
<p> Welcome to our blog page, we like to troll people here. </p>

<%= link_to 'Add a blog', new_blog_path %>

app/views/blog/new.html.erb
<h1> Please Fill Form </h1>
<%= form_with model: @Blog do |form| %>
    <%= form.label :title %>
    <%= form.text_field :title %>
        <br />
    <%= form.label :content %>
    <%= form.text_field :content %>
        <%= form.submit  'Add Blog' %>
<% end %>
        <br />
 <%= link_to 'back to main page', blogs_path %>

app/views/blog/show.html.erb
<h1> Title: <%= @blog.title %> </h1>

<h1> Content: <%= @blog.content %> </h1>
<%= link_to 'back to main page', blogs_path %>
<%= link_to 'Edit The Blog', edit_blog_path(@blog) %>
<%= button_to 'Delete Blog', delete_blog_path(@blog), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>

</html>